/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedCaregiverAlertsRouteImport } from './routes/_authenticated/caregiver/alerts'
import { Route as AuthenticatedCaregiverCarePlansRouteImport } from './routes/_authenticated/caregiver/care-plans'
import { Route as AuthenticatedCaregiverDashboardRouteImport } from './routes/_authenticated/caregiver/dashboard'
import { Route as AuthenticatedCaregiverNotesRouteImport } from './routes/_authenticated/caregiver/notes'
import { Route as AuthenticatedCaregiverProfileRouteImport } from './routes/_authenticated/caregiver/profile'
import { Route as AuthenticatedCaregiverSosRouteImport } from './routes/_authenticated/caregiver/sos'
import { Route as AuthenticatedDoctorAlertsRouteImport } from './routes/_authenticated/doctor/alerts'
import { Route as AuthenticatedDoctorCarePlansRouteImport } from './routes/_authenticated/doctor/care-plans'
import { Route as AuthenticatedDoctorDashboardRouteImport } from './routes/_authenticated/doctor/dashboard'
import { Route as AuthenticatedDoctorNotesRouteImport } from './routes/_authenticated/doctor/notes'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor/profile'
import { Route as AuthenticatedDoctorReportsRouteImport } from './routes/_authenticated/doctor/reports'
import { Route as AuthenticatedDoctorSettingsRouteImport } from './routes/_authenticated/doctor/settings'
import { Route as AuthenticatedDoctorSosRouteImport } from './routes/_authenticated/doctor/sos'
import { Route as AuthenticatedPatientAdherenceRouteImport } from './routes/_authenticated/patient/adherence'
import { Route as AuthenticatedPatientAlertsRouteImport } from './routes/_authenticated/patient/alerts'
import { Route as AuthenticatedPatientAssistantRouteImport } from './routes/_authenticated/patient/assistant'
import { Route as AuthenticatedPatientDashboardRouteImport } from './routes/_authenticated/patient/dashboard'
import { Route as AuthenticatedPatientHistoryRouteImport } from './routes/_authenticated/patient/history'
import { Route as AuthenticatedPatientMonitoringRouteImport } from './routes/_authenticated/patient/monitoring'
import { Route as AuthenticatedPatientNebulizationRouteImport } from './routes/_authenticated/patient/nebulization'
import { Route as AuthenticatedPatientNebulizerRouteImport } from './routes/_authenticated/patient/nebulizer'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient/profile'
import { Route as AuthenticatedPatientReportsRouteImport } from './routes/_authenticated/patient/reports'
import { Route as AuthenticatedPatientSettingsRouteImport } from './routes/_authenticated/patient/settings'
import { Route as AuthenticatedSuperAdminDashboardRouteImport } from './routes/_authenticated/super-admin/dashboard'
import { Route as AuthenticatedCaregiverPatientsIndexRouteImport } from './routes/_authenticated/caregiver/patients.index'
import { Route as AuthenticatedCaregiverPatientsPatientIdRouteImport } from './routes/_authenticated/caregiver/patients.$patientId'
import { Route as AuthenticatedDoctorPatientsIndexRouteImport } from './routes/_authenticated/doctor/patients.index'
import { Route as AuthenticatedDoctorPatientsPatientIdRouteImport } from './routes/_authenticated/doctor/patients.$patientId'
import { Route as ApiPublicCronEvaluateAlertsRouteImport } from './routes/api/public/cron/evaluate-alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverAlertsRoute =
  AuthenticatedCaregiverAlertsRouteImport.update({
    id: '/caregiver/alerts',
    path: '/caregiver/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverCarePlansRoute =
  AuthenticatedCaregiverCarePlansRouteImport.update({
    id: '/caregiver/care-plans',
    path: '/caregiver/care-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverDashboardRoute =
  AuthenticatedCaregiverDashboardRouteImport.update({
    id: '/caregiver/dashboard',
    path: '/caregiver/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverNotesRoute =
  AuthenticatedCaregiverNotesRouteImport.update({
    id: '/caregiver/notes',
    path: '/caregiver/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverProfileRoute =
  AuthenticatedCaregiverProfileRouteImport.update({
    id: '/caregiver/profile',
    path: '/caregiver/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverSosRoute =
  AuthenticatedCaregiverSosRouteImport.update({
    id: '/caregiver/sos',
    path: '/caregiver/sos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorAlertsRoute =
  AuthenticatedDoctorAlertsRouteImport.update({
    id: '/doctor/alerts',
    path: '/doctor/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorCarePlansRoute =
  AuthenticatedDoctorCarePlansRouteImport.update({
    id: '/doctor/care-plans',
    path: '/doctor/care-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorDashboardRoute =
  AuthenticatedDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorNotesRoute =
  AuthenticatedDoctorNotesRouteImport.update({
    id: '/doctor/notes',
    path: '/doctor/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/doctor/profile',
    path: '/doctor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorReportsRoute =
  AuthenticatedDoctorReportsRouteImport.update({
    id: '/doctor/reports',
    path: '/doctor/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorSettingsRoute =
  AuthenticatedDoctorSettingsRouteImport.update({
    id: '/doctor/settings',
    path: '/doctor/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorSosRoute = AuthenticatedDoctorSosRouteImport.update({
  id: '/doctor/sos',
  path: '/doctor/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientAdherenceRoute =
  AuthenticatedPatientAdherenceRouteImport.update({
    id: '/patient/adherence',
    path: '/patient/adherence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientAlertsRoute =
  AuthenticatedPatientAlertsRouteImport.update({
    id: '/patient/alerts',
    path: '/patient/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientAssistantRoute =
  AuthenticatedPatientAssistantRouteImport.update({
    id: '/patient/assistant',
    path: '/patient/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientDashboardRoute =
  AuthenticatedPatientDashboardRouteImport.update({
    id: '/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientHistoryRoute =
  AuthenticatedPatientHistoryRouteImport.update({
    id: '/patient/history',
    path: '/patient/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientMonitoringRoute =
  AuthenticatedPatientMonitoringRouteImport.update({
    id: '/patient/monitoring',
    path: '/patient/monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientNebulizationRoute =
  AuthenticatedPatientNebulizationRouteImport.update({
    id: '/patient/nebulization',
    path: '/patient/nebulization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientNebulizerRoute =
  AuthenticatedPatientNebulizerRouteImport.update({
    id: '/patient/nebulizer',
    path: '/patient/nebulizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/patient/profile',
    path: '/patient/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientReportsRoute =
  AuthenticatedPatientReportsRouteImport.update({
    id: '/patient/reports',
    path: '/patient/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientSettingsRoute =
  AuthenticatedPatientSettingsRouteImport.update({
    id: '/patient/settings',
    path: '/patient/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminDashboardRoute =
  AuthenticatedSuperAdminDashboardRouteImport.update({
    id: '/super-admin/dashboard',
    path: '/super-admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverPatientsIndexRoute =
  AuthenticatedCaregiverPatientsIndexRouteImport.update({
    id: '/caregiver/patients/',
    path: '/caregiver/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverPatientsPatientIdRoute =
  AuthenticatedCaregiverPatientsPatientIdRouteImport.update({
    id: '/caregiver/patients/$patientId',
    path: '/caregiver/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorPatientsIndexRoute =
  AuthenticatedDoctorPatientsIndexRouteImport.update({
    id: '/doctor/patients/',
    path: '/doctor/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorPatientsPatientIdRoute =
  AuthenticatedDoctorPatientsPatientIdRouteImport.update({
    id: '/doctor/patients/$patientId',
    path: '/doctor/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronEvaluateAlertsRoute =
  ApiPublicCronEvaluateAlertsRouteImport.update({
    id: '/api/public/cron/evaluate-alerts',
    path: '/api/public/cron/evaluate-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/caregiver/alerts': typeof AuthenticatedCaregiverAlertsRoute
  '/caregiver/care-plans': typeof AuthenticatedCaregiverCarePlansRoute
  '/caregiver/dashboard': typeof AuthenticatedCaregiverDashboardRoute
  '/caregiver/notes': typeof AuthenticatedCaregiverNotesRoute
  '/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/caregiver/sos': typeof AuthenticatedCaregiverSosRoute
  '/doctor/alerts': typeof AuthenticatedDoctorAlertsRoute
  '/doctor/care-plans': typeof AuthenticatedDoctorCarePlansRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/notes': typeof AuthenticatedDoctorNotesRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/doctor/sos': typeof AuthenticatedDoctorSosRoute
  '/patient/adherence': typeof AuthenticatedPatientAdherenceRoute
  '/patient/alerts': typeof AuthenticatedPatientAlertsRoute
  '/patient/assistant': typeof AuthenticatedPatientAssistantRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/monitoring': typeof AuthenticatedPatientMonitoringRoute
  '/patient/nebulization': typeof AuthenticatedPatientNebulizationRoute
  '/patient/nebulizer': typeof AuthenticatedPatientNebulizerRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/reports': typeof AuthenticatedPatientReportsRoute
  '/patient/settings': typeof AuthenticatedPatientSettingsRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/caregiver/patients/$patientId': typeof AuthenticatedCaregiverPatientsPatientIdRoute
  '/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/caregiver/patients/': typeof AuthenticatedCaregiverPatientsIndexRoute
  '/doctor/patients/': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/caregiver/alerts': typeof AuthenticatedCaregiverAlertsRoute
  '/caregiver/care-plans': typeof AuthenticatedCaregiverCarePlansRoute
  '/caregiver/dashboard': typeof AuthenticatedCaregiverDashboardRoute
  '/caregiver/notes': typeof AuthenticatedCaregiverNotesRoute
  '/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/caregiver/sos': typeof AuthenticatedCaregiverSosRoute
  '/doctor/alerts': typeof AuthenticatedDoctorAlertsRoute
  '/doctor/care-plans': typeof AuthenticatedDoctorCarePlansRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/notes': typeof AuthenticatedDoctorNotesRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/doctor/sos': typeof AuthenticatedDoctorSosRoute
  '/patient/adherence': typeof AuthenticatedPatientAdherenceRoute
  '/patient/alerts': typeof AuthenticatedPatientAlertsRoute
  '/patient/assistant': typeof AuthenticatedPatientAssistantRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/patient/monitoring': typeof AuthenticatedPatientMonitoringRoute
  '/patient/nebulization': typeof AuthenticatedPatientNebulizationRoute
  '/patient/nebulizer': typeof AuthenticatedPatientNebulizerRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/reports': typeof AuthenticatedPatientReportsRoute
  '/patient/settings': typeof AuthenticatedPatientSettingsRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/caregiver/patients/$patientId': typeof AuthenticatedCaregiverPatientsPatientIdRoute
  '/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/caregiver/patients': typeof AuthenticatedCaregiverPatientsIndexRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/mobile': typeof MobileRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/caregiver/alerts': typeof AuthenticatedCaregiverAlertsRoute
  '/_authenticated/caregiver/care-plans': typeof AuthenticatedCaregiverCarePlansRoute
  '/_authenticated/caregiver/dashboard': typeof AuthenticatedCaregiverDashboardRoute
  '/_authenticated/caregiver/notes': typeof AuthenticatedCaregiverNotesRoute
  '/_authenticated/caregiver/profile': typeof AuthenticatedCaregiverProfileRoute
  '/_authenticated/caregiver/sos': typeof AuthenticatedCaregiverSosRoute
  '/_authenticated/doctor/alerts': typeof AuthenticatedDoctorAlertsRoute
  '/_authenticated/doctor/care-plans': typeof AuthenticatedDoctorCarePlansRoute
  '/_authenticated/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/_authenticated/doctor/notes': typeof AuthenticatedDoctorNotesRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/doctor/reports': typeof AuthenticatedDoctorReportsRoute
  '/_authenticated/doctor/settings': typeof AuthenticatedDoctorSettingsRoute
  '/_authenticated/doctor/sos': typeof AuthenticatedDoctorSosRoute
  '/_authenticated/patient/adherence': typeof AuthenticatedPatientAdherenceRoute
  '/_authenticated/patient/alerts': typeof AuthenticatedPatientAlertsRoute
  '/_authenticated/patient/assistant': typeof AuthenticatedPatientAssistantRoute
  '/_authenticated/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/_authenticated/patient/history': typeof AuthenticatedPatientHistoryRoute
  '/_authenticated/patient/monitoring': typeof AuthenticatedPatientMonitoringRoute
  '/_authenticated/patient/nebulization': typeof AuthenticatedPatientNebulizationRoute
  '/_authenticated/patient/nebulizer': typeof AuthenticatedPatientNebulizerRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/patient/reports': typeof AuthenticatedPatientReportsRoute
  '/_authenticated/patient/settings': typeof AuthenticatedPatientSettingsRoute
  '/_authenticated/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/_authenticated/caregiver/patients/$patientId': typeof AuthenticatedCaregiverPatientsPatientIdRoute
  '/_authenticated/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/api/public/cron/evaluate-alerts': typeof ApiPublicCronEvaluateAlertsRoute
  '/_authenticated/caregiver/patients/': typeof AuthenticatedCaregiverPatientsIndexRoute
  '/_authenticated/doctor/patients/': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/mobile'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin/dashboard'
    | '/caregiver/alerts'
    | '/caregiver/care-plans'
    | '/caregiver/dashboard'
    | '/caregiver/notes'
    | '/caregiver/profile'
    | '/caregiver/sos'
    | '/doctor/alerts'
    | '/doctor/care-plans'
    | '/doctor/dashboard'
    | '/doctor/notes'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/doctor/sos'
    | '/patient/adherence'
    | '/patient/alerts'
    | '/patient/assistant'
    | '/patient/dashboard'
    | '/patient/history'
    | '/patient/monitoring'
    | '/patient/nebulization'
    | '/patient/nebulizer'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/settings'
    | '/super-admin/dashboard'
    | '/caregiver/patients/$patientId'
    | '/doctor/patients/$patientId'
    | '/api/public/cron/evaluate-alerts'
    | '/caregiver/patients/'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/delete-account'
    | '/mobile'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin/dashboard'
    | '/caregiver/alerts'
    | '/caregiver/care-plans'
    | '/caregiver/dashboard'
    | '/caregiver/notes'
    | '/caregiver/profile'
    | '/caregiver/sos'
    | '/doctor/alerts'
    | '/doctor/care-plans'
    | '/doctor/dashboard'
    | '/doctor/notes'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/doctor/sos'
    | '/patient/adherence'
    | '/patient/alerts'
    | '/patient/assistant'
    | '/patient/dashboard'
    | '/patient/history'
    | '/patient/monitoring'
    | '/patient/nebulization'
    | '/patient/nebulizer'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/settings'
    | '/super-admin/dashboard'
    | '/caregiver/patients/$patientId'
    | '/doctor/patients/$patientId'
    | '/api/public/cron/evaluate-alerts'
    | '/caregiver/patients'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/delete-account'
    | '/mobile'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/caregiver/alerts'
    | '/_authenticated/caregiver/care-plans'
    | '/_authenticated/caregiver/dashboard'
    | '/_authenticated/caregiver/notes'
    | '/_authenticated/caregiver/profile'
    | '/_authenticated/caregiver/sos'
    | '/_authenticated/doctor/alerts'
    | '/_authenticated/doctor/care-plans'
    | '/_authenticated/doctor/dashboard'
    | '/_authenticated/doctor/notes'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/doctor/reports'
    | '/_authenticated/doctor/settings'
    | '/_authenticated/doctor/sos'
    | '/_authenticated/patient/adherence'
    | '/_authenticated/patient/alerts'
    | '/_authenticated/patient/assistant'
    | '/_authenticated/patient/dashboard'
    | '/_authenticated/patient/history'
    | '/_authenticated/patient/monitoring'
    | '/_authenticated/patient/nebulization'
    | '/_authenticated/patient/nebulizer'
    | '/_authenticated/patient/profile'
    | '/_authenticated/patient/reports'
    | '/_authenticated/patient/settings'
    | '/_authenticated/super-admin/dashboard'
    | '/_authenticated/caregiver/patients/$patientId'
    | '/_authenticated/doctor/patients/$patientId'
    | '/api/public/cron/evaluate-alerts'
    | '/_authenticated/caregiver/patients/'
    | '/_authenticated/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  MobileRoute: typeof MobileRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronEvaluateAlertsRoute: typeof ApiPublicCronEvaluateAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/alerts': {
      id: '/_authenticated/caregiver/alerts'
      path: '/caregiver/alerts'
      fullPath: '/caregiver/alerts'
      preLoaderRoute: typeof AuthenticatedCaregiverAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/care-plans': {
      id: '/_authenticated/caregiver/care-plans'
      path: '/caregiver/care-plans'
      fullPath: '/caregiver/care-plans'
      preLoaderRoute: typeof AuthenticatedCaregiverCarePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/dashboard': {
      id: '/_authenticated/caregiver/dashboard'
      path: '/caregiver/dashboard'
      fullPath: '/caregiver/dashboard'
      preLoaderRoute: typeof AuthenticatedCaregiverDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/notes': {
      id: '/_authenticated/caregiver/notes'
      path: '/caregiver/notes'
      fullPath: '/caregiver/notes'
      preLoaderRoute: typeof AuthenticatedCaregiverNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/profile': {
      id: '/_authenticated/caregiver/profile'
      path: '/caregiver/profile'
      fullPath: '/caregiver/profile'
      preLoaderRoute: typeof AuthenticatedCaregiverProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/sos': {
      id: '/_authenticated/caregiver/sos'
      path: '/caregiver/sos'
      fullPath: '/caregiver/sos'
      preLoaderRoute: typeof AuthenticatedCaregiverSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/alerts': {
      id: '/_authenticated/doctor/alerts'
      path: '/doctor/alerts'
      fullPath: '/doctor/alerts'
      preLoaderRoute: typeof AuthenticatedDoctorAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/care-plans': {
      id: '/_authenticated/doctor/care-plans'
      path: '/doctor/care-plans'
      fullPath: '/doctor/care-plans'
      preLoaderRoute: typeof AuthenticatedDoctorCarePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/dashboard': {
      id: '/_authenticated/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/notes': {
      id: '/_authenticated/doctor/notes'
      path: '/doctor/notes'
      fullPath: '/doctor/notes'
      preLoaderRoute: typeof AuthenticatedDoctorNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/reports': {
      id: '/_authenticated/doctor/reports'
      path: '/doctor/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof AuthenticatedDoctorReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/settings': {
      id: '/_authenticated/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof AuthenticatedDoctorSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/sos': {
      id: '/_authenticated/doctor/sos'
      path: '/doctor/sos'
      fullPath: '/doctor/sos'
      preLoaderRoute: typeof AuthenticatedDoctorSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/adherence': {
      id: '/_authenticated/patient/adherence'
      path: '/patient/adherence'
      fullPath: '/patient/adherence'
      preLoaderRoute: typeof AuthenticatedPatientAdherenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/alerts': {
      id: '/_authenticated/patient/alerts'
      path: '/patient/alerts'
      fullPath: '/patient/alerts'
      preLoaderRoute: typeof AuthenticatedPatientAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/assistant': {
      id: '/_authenticated/patient/assistant'
      path: '/patient/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof AuthenticatedPatientAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/dashboard': {
      id: '/_authenticated/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof AuthenticatedPatientDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/history': {
      id: '/_authenticated/patient/history'
      path: '/patient/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof AuthenticatedPatientHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/monitoring': {
      id: '/_authenticated/patient/monitoring'
      path: '/patient/monitoring'
      fullPath: '/patient/monitoring'
      preLoaderRoute: typeof AuthenticatedPatientMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/nebulization': {
      id: '/_authenticated/patient/nebulization'
      path: '/patient/nebulization'
      fullPath: '/patient/nebulization'
      preLoaderRoute: typeof AuthenticatedPatientNebulizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/nebulizer': {
      id: '/_authenticated/patient/nebulizer'
      path: '/patient/nebulizer'
      fullPath: '/patient/nebulizer'
      preLoaderRoute: typeof AuthenticatedPatientNebulizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/reports': {
      id: '/_authenticated/patient/reports'
      path: '/patient/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof AuthenticatedPatientReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/settings': {
      id: '/_authenticated/patient/settings'
      path: '/patient/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof AuthenticatedPatientSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/dashboard': {
      id: '/_authenticated/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/patients/': {
      id: '/_authenticated/caregiver/patients/'
      path: '/caregiver/patients'
      fullPath: '/caregiver/patients/'
      preLoaderRoute: typeof AuthenticatedCaregiverPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver/patients/$patientId': {
      id: '/_authenticated/caregiver/patients/$patientId'
      path: '/caregiver/patients/$patientId'
      fullPath: '/caregiver/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedCaregiverPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/patients/': {
      id: '/_authenticated/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/patients/$patientId': {
      id: '/_authenticated/doctor/patients/$patientId'
      path: '/doctor/patients/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/evaluate-alerts': {
      id: '/api/public/cron/evaluate-alerts'
      path: '/api/public/cron/evaluate-alerts'
      fullPath: '/api/public/cron/evaluate-alerts'
      preLoaderRoute: typeof ApiPublicCronEvaluateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedCaregiverAlertsRoute: typeof AuthenticatedCaregiverAlertsRoute
  AuthenticatedCaregiverCarePlansRoute: typeof AuthenticatedCaregiverCarePlansRoute
  AuthenticatedCaregiverDashboardRoute: typeof AuthenticatedCaregiverDashboardRoute
  AuthenticatedCaregiverNotesRoute: typeof AuthenticatedCaregiverNotesRoute
  AuthenticatedCaregiverProfileRoute: typeof AuthenticatedCaregiverProfileRoute
  AuthenticatedCaregiverSosRoute: typeof AuthenticatedCaregiverSosRoute
  AuthenticatedDoctorAlertsRoute: typeof AuthenticatedDoctorAlertsRoute
  AuthenticatedDoctorCarePlansRoute: typeof AuthenticatedDoctorCarePlansRoute
  AuthenticatedDoctorDashboardRoute: typeof AuthenticatedDoctorDashboardRoute
  AuthenticatedDoctorNotesRoute: typeof AuthenticatedDoctorNotesRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorReportsRoute: typeof AuthenticatedDoctorReportsRoute
  AuthenticatedDoctorSettingsRoute: typeof AuthenticatedDoctorSettingsRoute
  AuthenticatedDoctorSosRoute: typeof AuthenticatedDoctorSosRoute
  AuthenticatedPatientAdherenceRoute: typeof AuthenticatedPatientAdherenceRoute
  AuthenticatedPatientAlertsRoute: typeof AuthenticatedPatientAlertsRoute
  AuthenticatedPatientAssistantRoute: typeof AuthenticatedPatientAssistantRoute
  AuthenticatedPatientDashboardRoute: typeof AuthenticatedPatientDashboardRoute
  AuthenticatedPatientHistoryRoute: typeof AuthenticatedPatientHistoryRoute
  AuthenticatedPatientMonitoringRoute: typeof AuthenticatedPatientMonitoringRoute
  AuthenticatedPatientNebulizationRoute: typeof AuthenticatedPatientNebulizationRoute
  AuthenticatedPatientNebulizerRoute: typeof AuthenticatedPatientNebulizerRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientReportsRoute: typeof AuthenticatedPatientReportsRoute
  AuthenticatedPatientSettingsRoute: typeof AuthenticatedPatientSettingsRoute
  AuthenticatedSuperAdminDashboardRoute: typeof AuthenticatedSuperAdminDashboardRoute
  AuthenticatedCaregiverPatientsPatientIdRoute: typeof AuthenticatedCaregiverPatientsPatientIdRoute
  AuthenticatedDoctorPatientsPatientIdRoute: typeof AuthenticatedDoctorPatientsPatientIdRoute
  AuthenticatedCaregiverPatientsIndexRoute: typeof AuthenticatedCaregiverPatientsIndexRoute
  AuthenticatedDoctorPatientsIndexRoute: typeof AuthenticatedDoctorPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedCaregiverAlertsRoute: AuthenticatedCaregiverAlertsRoute,
  AuthenticatedCaregiverCarePlansRoute: AuthenticatedCaregiverCarePlansRoute,
  AuthenticatedCaregiverDashboardRoute: AuthenticatedCaregiverDashboardRoute,
  AuthenticatedCaregiverNotesRoute: AuthenticatedCaregiverNotesRoute,
  AuthenticatedCaregiverProfileRoute: AuthenticatedCaregiverProfileRoute,
  AuthenticatedCaregiverSosRoute: AuthenticatedCaregiverSosRoute,
  AuthenticatedDoctorAlertsRoute: AuthenticatedDoctorAlertsRoute,
  AuthenticatedDoctorCarePlansRoute: AuthenticatedDoctorCarePlansRoute,
  AuthenticatedDoctorDashboardRoute: AuthenticatedDoctorDashboardRoute,
  AuthenticatedDoctorNotesRoute: AuthenticatedDoctorNotesRoute,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedDoctorReportsRoute: AuthenticatedDoctorReportsRoute,
  AuthenticatedDoctorSettingsRoute: AuthenticatedDoctorSettingsRoute,
  AuthenticatedDoctorSosRoute: AuthenticatedDoctorSosRoute,
  AuthenticatedPatientAdherenceRoute: AuthenticatedPatientAdherenceRoute,
  AuthenticatedPatientAlertsRoute: AuthenticatedPatientAlertsRoute,
  AuthenticatedPatientAssistantRoute: AuthenticatedPatientAssistantRoute,
  AuthenticatedPatientDashboardRoute: AuthenticatedPatientDashboardRoute,
  AuthenticatedPatientHistoryRoute: AuthenticatedPatientHistoryRoute,
  AuthenticatedPatientMonitoringRoute: AuthenticatedPatientMonitoringRoute,
  AuthenticatedPatientNebulizationRoute: AuthenticatedPatientNebulizationRoute,
  AuthenticatedPatientNebulizerRoute: AuthenticatedPatientNebulizerRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientReportsRoute: AuthenticatedPatientReportsRoute,
  AuthenticatedPatientSettingsRoute: AuthenticatedPatientSettingsRoute,
  AuthenticatedSuperAdminDashboardRoute: AuthenticatedSuperAdminDashboardRoute,
  AuthenticatedCaregiverPatientsPatientIdRoute:
    AuthenticatedCaregiverPatientsPatientIdRoute,
  AuthenticatedDoctorPatientsPatientIdRoute:
    AuthenticatedDoctorPatientsPatientIdRoute,
  AuthenticatedCaregiverPatientsIndexRoute:
    AuthenticatedCaregiverPatientsIndexRoute,
  AuthenticatedDoctorPatientsIndexRoute: AuthenticatedDoctorPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  MobileRoute: MobileRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronEvaluateAlertsRoute: ApiPublicCronEvaluateAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
